### ISSUE TITLE
Poder reducir una expresión a su resultado

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/function-laboratory#13]
Una posibilidad podría ser haciendo click derecho y teniendo una opción de "Reducir". Otra opción es tener un botoncito más cheto.

- Esto debería reemplazar los bloques que componen la expresión por uno con el resultado.
- Solamente lo habilitaría en funciones completamente aplicadas.

**Comment by JuanFdS** [comment]
Queremos que se pueda rollbackear eso?, tipo poder volver a verla desaplicada?

**Comment by PalumboN** [comment]
No me lo esperaba, pero si ya lo tenés hecho como vi en el mensaje de telegram de una!! :smiley:
