### ISSUE TITLE
Nested compositions don't perform typechecks and show errors on console

### ISSUE THREAD

**Issue by JuanFdS** [uqbar-project/function-laboratory#3]
![nestedCompositionDoesNotTypeCHeck](https://user-images.githubusercontent.com/11432672/79055845-93e3c200-7c26-11ea-8034-9d1ae6849304.gif)

**Comment by PalumboN** [comment]
Para arreglar esto necesitamos soportar tipado de orden superior y que la composición deje de ser un caso especial de función.
