### ISSUE TITLE
El filter no anda

### ISSUE THREAD

**Issue by JuanFdS** [uqbar-project/function-laboratory#51]
TODO: completar esto explicando un poco más (?

**Comment by asanzo** [comment]
Yo cambiaría el nombre del issue a "all y filter no reducen" y pondría estas dos imágenes:

![Selección_999(707)](https://user-images.githubusercontent.com/5421992/117977029-cb7bdc80-b306-11eb-8d85-f4c07f6275fa.png)

![Selección_999(707) (4)](https://user-images.githubusercontent.com/5421992/117978208-03cfea80-b308-11eb-9cf5-c8fd6330f4d9.png)


@PalumboN
