### ISSUE TITLE
Error al querer reducir una expresión

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/function-laboratory#52]
@PalumboN  @JuanFdS Les mando la forma de reproducirlo, no lo intenté todavía en Firefox, solo en Chrome:

![reductionProblem](https://user-images.githubusercontent.com/4549002/115475779-c69b9f80-a216-11eb-871c-2a86f9237d8f.gif)

Abrazo y las funciones están muy buenas!!

**Comment by fdodino** [comment]
Ah, ya entendí por qué: le complica la aplicación parcial de (1 +).

```hs
(even . length) "Fernando"
```

lo resolvió perfectamente.

**Comment by PalumboN** [comment]
Con la nueva forma de reducir los bloques esto ya se arregló :tada:
![Peek 2021-05-02 12-54](https://user-images.githubusercontent.com/4098184/116819237-8eb12800-ab45-11eb-8542-ab6a0be6c698.gif)
